version: '3.7'

volumes:
  dependency-track:
  https-portal_certs:
  https-portal_logs:

services:

  https-portal:
    image: steveltn/https-portal:${HTTPS_PORTAL_VERSION:-1}
    environment:
      DOMAINS: >
        api.dependencytrack.test -> http://dtrack-apiserver:8080,
        dependencytrack.test -> http://dtrack-frontend:8080
      CLIENT_MAX_BODY_SIZE: 128M
      SERVER_NAMES_HASH_BUCKET_SIZE: 1024
      STAGE: local
    volumes:
      - https-portal_certs:/var/lib/https-portal
      - https-portal_logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dtrack-frontend

  dtrack-apiserver:
    image: dependencytrack/apiserver
    deploy:
      resources:
        limits:
          memory: 12288m
    expose:
      - 8080
    volumes:
      - 'dependency-track:/data'

  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=https://api.dependencytrack.test
    expose:
      - 8080
